### ISSUE TITLE
Error during the update

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/poppy-installer#25]
On a poppy-humanoid with an odroid U3, I got this error after running the poppy-configure script:

```
POPPY_GROUPS=adm,dialout,sudo,audio,video,plugdev,netdev
poppy-configure.sh: 40: poppy-configure.sh: Syntax error: "}" unexpected (expecting "fi")
```

**Comment by show0k** [comment]
Are you sure you started it with
```
bash poppy-configure.sh rpi poppy-humanoid
``` ?

**Comment by matthieu-lapeyre** [comment]
```
bash poppy-configure.sh odroid poppy-humanoid
```
Probably with sudo

**Comment by show0k** [comment]
Are you sure that poppy-configure.sh was not already present on the disk ?
Wget does not overwrite files. If it was, you have probably a poppy-configure.sh .1 on disk.

**Comment by matthieu-lapeyre** [comment]
poppy-configure.sh was probably here...

Is there an option to overwrite file with wget ? For me it's a problem if we cannot obtain the desired result by following step-by-step the documentation.

**Comment by show0k** [comment]
It is fixed in the doc now.
