### ISSUE TITLE
ajout de python-dev

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy-installer#8]
On ne peut pas compiler les dépendances C sans python-dev

**Comment by pierre-rouanet** [comment]
A quelle dépendance tu penses ? Dans opencv je l'ai mis en dép. On pourrait également l'installer par défaut tu me diras.

**Comment by show0k** [comment]
L'install ma crashé à la gueule en compilant python-zmq via pip. Je 
pense donc que c'est une bonne idée de l'installer par défaut.

**Comment by pierre-rouanet** [comment]
Fait.
