### ISSUE TITLE
liblapack3gf manquante

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy-installer#9]
Il l'a faut pour numpy et scipy

**Comment by pierre-rouanet** [comment]
numpy et scipy sont maintenant installé via package debian. Donc plus de problème ?

**Comment by show0k** [comment]
C'est vrai mais si jamais on veut la dernière version via pip, autant 
avoir télécharger les dépendances qui sont "difficile" à trouver, non ?

**Comment by pierre-rouanet** [comment]
Tu veux dire qu'elle n'est pas installée comme dépendance du paquet python-scipy ? Dans ce cas effectivement c'est sans doute mieux de l'ajouter.
